# Your name and what you do
name: Sarit Moses
bio: Master's student at WIS

description: Sarit Moses's Personal Website

# Profile picture
picture: /assets/images/profile%20small%20.jpg

# your url: http://USERNAME.github.io
url: https://sarit-moses.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
facebook: Sarit Moses
#twitter: mytwitter
linkedin: Sarit Moses
#github: mygithub
email: sarit5761@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Python
    - R
    - Lab experience - microbiology, molecular biology
    - Fluent Hebrew and English   

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Eve:
        name: ResearchGate profile
        description: 4 papers published before the age of 21
        url: https://www.researchgate.net/profile/Sarit-Moses
    World-Cup-History:
        name: Genetics of autism
        description: Research assistant for 2 years in a neuroscience lab
        url: https://neurogenetics.huji.ac.il/
    


# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
